### ISSUE TITLE
node launch.js 报错

### ISSUE THREAD

**Issue by Johnson-code** [nlmayday/niuniu#4]
![image](https://user-images.githubusercontent.com/20038482/59907246-37b47500-943d-11e9-97b3-076510e0a67b.png)
运行报错，控制台显示
![image](https://user-images.githubusercontent.com/20038482/59907289-54e94380-943d-11e9-86ab-263be332b206.png)

**Comment by nlmayday** [comment]
数据库没有配置好吧
