### ISSUE TITLE
用微信开发者工具加载完成以后卡住不会动了

### ISSUE THREAD

**Issue by DickLicha** [nlmayday/niuniu#6]
![image](https://user-images.githubusercontent.com/21870645/61341924-ff0c8d80-a87a-11e9-9172-c3c5bf49870e.png)
这是w我哪里配置错误了吗

**Comment by nlmayday** [comment]
我没有在微信开发者工具里面调试过，建议先在浏览器里面跑通，再在开发者工具调试。这周双休我试一下先

**Comment by DickLicha** [comment]
嗯，在浏览器启动微信登录点击没有反应

**Comment by nlmayday** [comment]
微信的上面有一个按钮 是游客登陆的 你可以点那个进去跑一下，然后微信那些是要配置appid和key的

**Comment by DickLicha** [comment]
![image](https://user-images.githubusercontent.com/21870645/61517627-4ab96580-aa3a-11e9-9043-6a8840d2a609.png)

**Comment by nlmayday** [comment]
服务器的地址不对  或者端口要改

**Comment by nlmayday** [comment]
已修改
