### ISSUE TITLE
很不错的项目啊，老哥

### ISSUE THREAD

**Issue by ghostxbh** [nlmayday/niuniu#7]
很不错的项目！就是文档少了点，老哥，还有没有麻将之类的源码？

**Comment by nlmayday** [comment]
有C++的 没有时间整理 不好放出来

**Comment by ghostxbh** [comment]
老哥是游戏公司的么？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: nl <notifications@github.com>
发送时间: Thursday, July 18, 2019 9:17:18 AM
收件人: nlmayday/niuniu
抄送: ghostxbh; Author
主题: Re: [nlmayday/niuniu] 很不错的项目啊，老哥 (#7)


有C++的 没有时间整理 不好放出来

―

**Comment by nlmayday** [comment]
是的 这个不是公司的代码

**Comment by ghostxbh** [comment]
嗯，是的，大家有时间都会写属于自己的开源项目

**Comment by nlmayday** [comment]
不是我写的 我只是整理了一下
